### PR TITLE
Change default cookie samesite setting to Lax

### PR DESCRIPTION
**Pull request by ranok**
Modern browsers treat cookies without an explicit samesite setting as Lax now, not None. This prevents you from being able to set it to None if needed (in conjunction with Secure).

### CODE REVIEW

**Comment by ranok** [comment]
Source for the change: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#cookies_without_samesite_default_to_samesitelax

**Comment by ringabout** [comment]
> Cookies will be sent in all contexts, i.e. in responses to both first-party and cross-site requests. If SameSite=None is set, the cookie [Secure](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#secure) attribute must also be set (or the cookie will be blocked).

It seems that if supporting `SameSite=None`, `secure` should be enabled too, like using a doAssert.

**Comment by ranok** [comment]
That seems fair. I am pretty new to Nim, so if I take a stab at it tomorrow you can let me know if I am doing it in the idiomatic way?

**Comment by ringabout** [comment]
Sure thing! Thanks for your efforts. See also https://github.com/nim-lang/Nim/blob/7dc80a7fefb0d2cecbdc2696c71ea2fa94d6aa76/lib/pure/cookies.nim#L70

**Comment by ranok** [comment]
Is there a preference for doAssert versus raising an exception?

**Comment by ringabout** [comment]
Imo, raising an exception is more suitable for this case.

**Comment by ranok** [comment]
Ok @ringabout I've added that in [515f43c](https://github.com/planety/cookiejar/pull/2/commits/515f43ce5d33bfb264e0d74b0fc603b13d10d43e) and confirmed it works in a Prologue app where I set the flags correctly (no error) and incorrectly (HTTP 500 or with debug=true it shows the exception to the browser).

**Comment by ringabout** [comment]
Good job!

**Comment by ringabout** [comment]
@ranok Hi, it seems to break the test
https://github.com/planety/cookiejar/actions/runs/4254814571/jobs/7401595834

```
Error: unhandled exception: /home/runner/work/cookiejar/cookiejar/tests/main/test.nim(48, 14) `setCookie(cookie) == fmt"{username}={password}; SameSite=Lax"`  [AssertionDefect]
```

**Comment by ranok** [comment]
Yes, since browsers moved the default to Lax, the SameSite will be elided if it's set to Lax (like it was for None previously). I'll update the test assertion to remove SameSite=Lax unless you'd rather we always include SameSite?

**Comment by ranok** [comment]
Here's the [commit changing the test file](https://github.com/ranok/cookiejar/commit/4aeb8c4b3cca638a76e73803a77189dc605e0772), if you want to be explicit I can change the cookie file to include SameSite for all options.

**Pull request merged**
